/**
 * User Signup API
 *
 * POST /api/auth/signup
 *
 * Registers a new user with email and password
 */

import type { VercelRequest, VercelResponse } from '@vercel/node';
import { supabaseAdmin } from '../../lib/supabase.js';
import { validateBody, signupSchema } from '../../lib/validation.js';

export default async function handler(
  req: VercelRequest,
  res: VercelResponse
) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({
      error: 'Method not allowed',
      message: 'Only POST requests are allowed'
    });
  }

  try {
    // Validate request body
    const { email, password, name } = validateBody(signupSchema, req.body);

    // Create user in Supabase Auth
    const { data: authData, error: authError } = await supabaseAdmin.auth.admin.createUser({
      email,
      password,
      email_confirm: true, // Auto-confirm email (for dev/testing, remove in prod)
      user_metadata: {
        name: name || null
      }
    });

    if (authError) {
      console.error('Signup error:', authError);

      // Handle specific errors
      if (authError.message.includes('already registered')) {
        return res.status(409).json({
          error: 'User already exists',
          message: 'An account with this email already exists'
        });
      }

      return res.status(400).json({
        error: 'Signup failed',
        message: authError.message
      });
    }

    if (!authData.user) {
      return res.status(500).json({
        error: 'Signup failed',
        message: 'User creation failed'
      });
    }

    // Generate pseudo_user_id for analytics (privacy protection)
    const { error: mappingError } = await supabaseAdmin
      .schema('pii')
      .from('user_id_mapping')
      .insert({
        real_user_id: authData.user.id
        // pseudo_user_id is auto-generated by database
      });

    if (mappingError) {
      console.error('Failed to create user ID mapping:', mappingError);
      // Don't fail the signup, but log the error
    }

    // Return success (tokens are handled by Supabase Auth on client side)
    return res.status(201).json({
      message: 'User created successfully',
      user: {
        id: authData.user.id,
        email: authData.user.email,
        created_at: authData.user.created_at
      }
    });

  } catch (error: any) {
    console.error('Signup error:', error);

    // Handle validation errors
    if (error.status === 400) {
      return res.status(400).json(error);
    }

    return res.status(500).json({
      error: 'Internal server error',
      message: error.message || 'An unexpected error occurred'
    });
  }
}
